import { useState, useMemo, useEffect, useRef } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useDebounce } from '../../../../hooks/useDebounce';
import DonationList from './DonationList';
import AddDonationModal from './AddDonationModal';
import EditPartialPaymentModal from './EditPartialPaymentModal';
import AddPartialPaymentModal from './AddPartialPaymentModal';
import usePermissions from '../../../../hooks/usePermissions';
import AdminPageHeader from '../../../../components/common/AdminPageHeader';
import { useGetAllDonationsQuery, useGetDonationStatusQuery, useResendWhatsAppMutation } from '../../../../services/donationApi';
import { useLazyGetGaushalasQuery } from '../../../../services/gaushalaApi';
import { useLazyGetKathasQuery } from '../../../../services/kathaApi';
import { useLazyGetCategoriesQuery } from '../../../../services/masterApi';
import { useDropdownPagination } from '../../../../hooks/useDropdownPagination';
import { useTable } from '../../../../hooks/useTable';
import { toast } from 'react-toastify';

const Donation = () => {
  const { hasPermission } = usePermissions();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingPartialDonation, setEditingPartialDonation] = useState(null);
  const [addingPartialDonation, setAddingPartialDonation] = useState(null);
  const [editingPayLaterDonation, setEditingPayLaterDonation] = useState(null);
  const [searchParams] = useSearchParams();

  const [resendWhatsApp, { isLoading: isResending }] = useResendWhatsAppMutation();

  const {
    filters,
    setFilters,
    handlePageChange,
    handleLimitChange,
    clearFilters,
  } = useTable({
    initialFilters: {
      search: '',
      startDate: '',
      endDate: '',
      minAmount: '',
      maxAmount: '',
      categoryId: '',
      city: '',
      gaushalaId: searchParams.get('gaushalaId') || '',
      kathaId: searchParams.get('kathaId') || '',
      status: '',
      page: 1,
      limit: 10,
      fetchAll: false,
      fields: 'id,amount,cause,status,paymentMode,createdAt,paymentDate,referenceName,slipUrl,paidAmount,remainingAmount,donationDate,slipNo,categoryId,gaushalaId,kathaId'
    }
  });

  const debouncedSearch = useDebounce(filters.search, 500);

  const queryFilters = useMemo(() => ({
    ...filters,
    search: debouncedSearch
  }), [filters, debouncedSearch]);

  // Track donation whose PDF is still being generated by the background worker.
  // While set, we poll the lightweight status endpoint (~100 bytes) instead of the full list.
  const [pendingDonationId, setPendingDonationId] = useState(null);
  const pendingTimeoutRef = useRef(null);

  // API calls
  const { data: donationsData, isLoading: loading, refetch: refetchDonations } = useGetAllDonationsQuery(queryFilters, {
    refetchOnFocus: true,
    refetchOnReconnect: true,
  });

  // Focused polling for the just-created donation's slip status.
  const { data: statusData } = useGetDonationStatusQuery(pendingDonationId, {
    skip: !pendingDonationId,
    pollingInterval: 2000,
  });

  // When the worker reports the slip is ready, stop polling and refresh the list.
  // Guarded by a ref so this runs once per donation id and doesn't loop.
  const handledIdRef = useRef(null);
  if (
    pendingDonationId &&
    statusData?.data?.ready &&
    handledIdRef.current !== pendingDonationId
  ) {
    handledIdRef.current = pendingDonationId;
    setPendingDonationId(null);
    refetchDonations();
  }

  // Safety: auto-stop focused polling after 30s regardless of outcome.
  const startSlipPolling = (id) => {
    if (!id) return;
    handledIdRef.current = null;
    setPendingDonationId(id);
    if (pendingTimeoutRef.current) clearTimeout(pendingTimeoutRef.current);
    pendingTimeoutRef.current = setTimeout(() => setPendingDonationId(null), 30000);
  };

  const handleDonationCreated = (id) => startSlipPolling(id);

  // Called by edit/add-partial modals after update. Only start polling if the
  // donation just became completed and the slip isn't generated yet.
  const handleDonationUpdated = (result) => {
    const d = result?.data;
    if (d?.id && d?.status === 'completed' && !d?.slipUrl) {
      startSlipPolling(d.id);
    }
  };

  useEffect(() => () => {
    if (pendingTimeoutRef.current) clearTimeout(pendingTimeoutRef.current);
  }, []);
  
  const [triggerGetGaushalas] = useLazyGetGaushalasQuery();
  const [triggerGetActiveGaushalas] = useLazyGetGaushalasQuery();
  const gaushalaPagination = useDropdownPagination(triggerGetGaushalas);
  const activeGaushalaPagination = useDropdownPagination(triggerGetActiveGaushalas, {
    additionalParams: { active: 'true' }
  });

  const [triggerGetKathas] = useLazyGetKathasQuery();
  const kathaPagination = useDropdownPagination(triggerGetKathas, {
  });

  const [triggerGetCategories] = useLazyGetCategoriesQuery();
  const [triggerGetActiveCategories] = useLazyGetCategoriesQuery();
  const categoryPagination = useDropdownPagination(triggerGetCategories, {
    additionalParams: { all: true }
  });
  const activeCategoryPagination = useDropdownPagination(triggerGetActiveCategories);

  const donations = donationsData?.data?.items || [];
  const pagination = {
    currentPage: donationsData?.data?.currentPage || 1,
    totalPages: donationsData?.data?.totalPages || 1,
    totalData: donationsData?.data?.totalData || 0,
    limit: donationsData?.data?.limit || 10
  };

  const handleAdd = () => {
    setIsModalOpen(true);
  };

  const handleFilterChange = (e) => {
    const { name, value, type, checked } = e.target;
    
    setFilters(prev => ({ 
      ...prev, 
      [name]: type === 'checkbox' ? checked : value,
      page: 1
    }));
  };

  const handleClearFilters = () => {
    clearFilters();
    gaushalaPagination.reset();
    kathaPagination.reset();
    categoryPagination.reset();
  };

  const handleDownloadSlip = (donation) => {
    if (donation.slipUrl) {
      window.open(donation.slipUrl, '_blank', 'noopener,noreferrer');
    } else if (donation.status === 'completed') {
      toast.info('રસીદ તૈયાર થઈ રહી છે, કૃપા કરીને થોડીવાર પછી પ્રયત્ન કરો.');
    }
  };

  const handleEditPartialPayment = (donation) => {
    setEditingPartialDonation(donation);
  };

  const handleAddPartialPayment = (donation) => {
    setAddingPartialDonation(donation);
  };

  const handleEditPayLater = (donation) => {
    setEditingPayLaterDonation(donation);
    setIsModalOpen(true);
  };

  const handleResendWhatsApp = async (donation) => {
    try {
      await resendWhatsApp(donation.id).unwrap();
      toast.success('WhatsApp message resent successfully');
    } catch (err) {
      toast.error(err?.data?.message || 'Failed to resend WhatsApp message');
    }
  };

  return (
    <div className="space-y-6">
      <AdminPageHeader 
        title="Donation Management" 
        subtitle="View and manage all received donations"
        buttonText={hasPermission('donations', 'entry') ? "Add Donation" : null}
        onButtonClick={handleAdd}
      />

      <DonationList 
        donations={donations}
        isLoading={loading}
        pagination={pagination}
        filters={filters}
        gaushalaPagination={gaushalaPagination}
        kathaPagination={kathaPagination}
        categoryPagination={categoryPagination}
        onFilterChange={handleFilterChange}
        onClearFilters={handleClearFilters}
        onPageChange={handlePageChange}
        onLimitChange={handleLimitChange}
        onDownloadSlip={handleDownloadSlip}
        onEditPartialPayment={handleEditPartialPayment}
        onAddPartialPayment={handleAddPartialPayment}
        onEditPayLater={handleEditPayLater}
        onResendWhatsApp={handleResendWhatsApp}
        isResending={isResending}
        hasPermission={hasPermission} 
      />

      {isModalOpen && (
        <AddDonationModal
          isOpen={isModalOpen}
          onClose={() => {
            setIsModalOpen(false);
            setEditingPayLaterDonation(null);
          }}
          gaushalaPagination={activeGaushalaPagination}
          kathaPagination={kathaPagination}
          categoryPagination={activeCategoryPagination}
          onCreated={handleDonationCreated}
          onUpdated={handleDonationUpdated}
          editingDonation={editingPayLaterDonation}
        />
      )}

      {editingPartialDonation && (
        <EditPartialPaymentModal
          isOpen={!!editingPartialDonation}
          donation={editingPartialDonation}
          onClose={() => setEditingPartialDonation(null)}
          onUpdated={handleDonationUpdated}
        />
      )}

      {addingPartialDonation && (
        <AddPartialPaymentModal
          isOpen={!!addingPartialDonation}
          donation={addingPartialDonation}
          onClose={() => setAddingPartialDonation(null)}
          onUpdated={handleDonationUpdated}
        />
      )}

    </div>
  );
};

export default Donation;
